In [6]:
import pandas
data_training = pandas.read_csv('Train1.csv') 
data_testing = pandas.read_csv('valid1.csv') 
data_final = pandas.read_csv('final1.csv')

In [7]:
group = data_training[['mvar33','actual_vote']].groupby('mvar33').agg(lambda x: ','.join(x)).apply(list)
from pandas import DataFrame
from collections import Counter
dicl = DataFrame.to_dict(group)
zips = {}
for i in dicl['actual_vote'].keys():
    l = dicl['actual_vote'][i].split(',')
    if len(Counter(l)) == 1:
        zips[i] = [Counter(l).most_common(1)[0][0],Counter(l).most_common(1)[0][1],'Noone',0]
    else:
        zips[i] = [Counter(l).most_common(1)[0][0],Counter(l).most_common(1)[0][1],Counter(l).most_common(2)[1][0],Counter(l).most_common(2)[1][1]]

In [8]:
df1 = pandas.read_csv('Train1.csv') 
df2 = pandas.read_csv('valid1.csv')
df3 = pandas.read_csv('final1.csv')
frames = [df1, df2, df3]
df4 = pandas.concat(frames)

In [9]:
x = set(df4['mvar33'].values)
y = x - set(df1['mvar33'].values) 
group = df4[['mvar33','party_voted_past']].groupby('mvar33').agg(lambda x: ','.join(x)).apply(list)
from pandas import DataFrame
from collections import Counter
dicl = DataFrame.to_dict(group)
for i in list(y):
    l = dicl['party_voted_past'][i].split(',')
    if len(Counter(l)) == 1:
        zips[i] = [Counter(l).most_common(1)[0][0],Counter(l).most_common(1)[0][1],'Noone',0]
    else:
        zips[i] = [Counter(l).most_common(1)[0][0],Counter(l).most_common(1)[0][1],Counter(l).most_common(2)[1][0],Counter(l).most_common(2)[1][1]]

In [12]:
A = 10
B = 2
C=1
D=1
E=1
Activity = {}
for data_training in [df1,df2,df3]:
        data_training['Ebony'] = A*data_training['mvar2'] + B*data_training['mvar7'] + C*data_training['mvar12']  + D*data_training['mvar17'] + E*data_training['mvar22']
        data_training['Odyssey'] = A*data_training['mvar4'] + B*data_training['mvar9'] + C*data_training['mvar14']  + D*data_training['mvar19'] +E*data_training['mvar24']
        data_training['Tokugawa'] = A*data_training['mvar3'] + B*data_training['mvar8'] + C*data_training['mvar13']  + D*data_training['mvar18'] +E*data_training['mvar23']
        data_training['Cosmos'] = A*data_training['mvar5'] + B*data_training['mvar10'] + C*data_training['mvar15']  + D*data_training['mvar20'] +E*data_training['mvar25']
        data_training['Centaur'] = A*data_training['mvar1'] + B*data_training['mvar6'] + C*data_training['mvar11']  + D*data_training['mvar16'] +E*data_training['mvar21']
        Cit_pref1 = []
        lev_pref1 = []
        lev_pref2 = []
        Cit_pref2 = []
        city_change = []
        ACTIVITY = []
        prefs = ['Centaur','Ebony','Tokugawa','Odyssey','Cosmos']
        for i in range(len(data_training)):
            level = [data_training['Centaur'].values[i],data_training['Ebony'].values[i],data_training['Tokugawa'].values[i],data_training['Odyssey'].values[i],data_training['Cosmos'].values[i]]
            lev_pref1.append(sorted(level)[-1])
            Cit_pref1.append(prefs[level.index(sorted(level)[-1])])
            lev_pref2.append(sorted(level)[-2])
            if sorted(level)[-2] == 0.0:
                Cit_pref2.append('NONE')
            else:
                Cit_pref2.append(prefs[level.index(sorted(level)[-2])])
            if data_training['mvar32'].values[i] == data_training['mvar33'].values[i]:
                city_change.append(0)
            else:
                city_change.append(1)          
        data_training['Cit_pref1'] = Cit_pref1
        data_training['lev_pref1'] = lev_pref1
        data_training['lev_pref2'] = lev_pref2
        data_training['Cit_pref2'] = Cit_pref2
        data_training['city_change'] = city_change
        
        
        
        
    
        ZIP_pref1 = []
        ZIP_pref2 = []
        ZIP_lev_pref1 = []
        ZIP_lev_pref2 = []
        for i in data_training['mvar33'].values:  
            ZIP_pref1.append(zips[i][0])
            ZIP_pref2.append(zips[i][2])
            ZIP_lev_pref1.append(zips[i][1])
            ZIP_lev_pref2.append(zips[i][3])
        data_training['ZIP_pref1'] =    ZIP_pref1
        data_training['ZIP_pref2'] =    ZIP_pref2
        data_training['ZIP_lev_pref1'] =    ZIP_lev_pref1
        data_training['ZIP_lev_pref2'] =    ZIP_lev_pref2
History_vote = []
Citizen_First_vote = []
for i in range(len(df1)):
    if df1['party_voted_past'].values[i] == df1['actual_vote'].values[i]:
        History_vote.append(1)
    else:
        History_vote.append(0)
for i in range(len(df1)):
    if df1['Cit_pref1'].values[i] == df1['actual_vote'].values[i]:
        Citizen_First_vote.append(1)
    else:
        Citizen_First_vote.append(0)
df1['History_vote'] = History_vote
df1['Citizen_First_vote'] = Citizen_First_vote

In [ ]:
Voted_first_priorty = []
History_vote = []
for i in range(len(df1)):
    if df1['Cit_pref1'].values[i] == df1['actual_vote'].values[i]:
        History_vote.append(1)
        Voted_first_priorty.append(i)
    else:
        History_vote.append(0)

In [417]:
df1.columns

Index([u'citizen_id', u'party_voted_past', u'mvar1', u'mvar2', u'mvar3',
       u'mvar4', u'mvar5', u'mvar6', u'mvar7', u'mvar8', u'mvar9', u'mvar10',
       u'mvar11', u'mvar12', u'mvar13', u'mvar14', u'mvar15', u'mvar16',
       u'mvar17', u'mvar18', u'mvar19', u'mvar20', u'mvar21', u'mvar22',
       u'mvar23', u'mvar24', u'mvar25', u'mvar26', u'mvar27', u'mvar28',
       u'mvar29', u'mvar30', u'mvar31', u'mvar32', u'mvar33', u'actual_vote',
       u'mvar34', u'mvar35', u'Ebony', u'Odyssey', u'Tokugawa', u'Cosmos',
       u'Centaur', u'Cit_pref1', u'lev_pref1', u'lev_pref2', u'Cit_pref2',
       u'city_change', u'ZIP_pref1', u'ZIP_pref2', u'ZIP_lev_pref1',
       u'ZIP_lev_pref2', u'History_vote', u'Citizen_First_vote',
       u'preferance_decision'],
      dtype='object')

In [522]:
L1 = []
L2 = []
L = []
LLL = []
for i in range(len(df1)):
    act = {}
    act['Ebony'] = [df1['mvar2'].values[i],df1['mvar7'].values[i],df1['mvar12'].values[i], df1['mvar17'].values[i],df1['mvar22'].values[i]]
    act['Odyssey'] = [df1['mvar4'].values[i],df1['mvar9'].values[i],df1['mvar14'].values[i], df1['mvar19'].values[i],df1['mvar24'].values[i]]
    act['Tokugawa'] = [df1['mvar3'].values[i],df1['mvar8'].values[i],df1['mvar13'].values[i], df1['mvar18'].values[i],df1['mvar23'].values[i]]
    act['Cosmos'] = [df1['mvar5'].values[i],df1['mvar10'].values[i],df1['mvar15'].values[i], df1['mvar20'].values[i],df1['mvar25'].values[i]]
    act['Centaur'] = [df1['mvar1'].values[i],df1['mvar6'].values[i],df1['mvar11'].values[i], df1['mvar16'].values[i],df1['mvar21'].values[i]]
    act['NONE'] = [0,0,0,0,0]
    L1.append(act[df1['Cit_pref1'].values[i]])
    L2.append(act[df1['Cit_pref2'].values[i]])
    L.append(act[df1['Cit_pref1'].values[i]]+act[df1['Cit_pref2'].values[i]]+[df1['ZIP_lev_pref1'].values[i],df1['ZIP_lev_pref2'].values[i]])

In [548]:
L1 = np.array(L1)
L2 = np.array(L2)
L = L1-L2

In [549]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(L, Y, test_size=0.25, random_state=0)
clf = GradientBoostingClassifier()
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
y_pred_proba = clf.predict_proba(X_test)
y_test = np.array(y_test)

In [550]:
clf.feature_importances_

array([ 0.30706475,  0.20555575,  0.106362  ,  0.20296511,  0.17805239])

In [544]:
y_pred_confidence = []
for i in range(len(y_pred)):
    if y_pred_proba[i][0]*100 >= 70 or y_pred_proba[i][1]*100 >= 70:
        y_pred_confidence.append(i)

In [545]:
from sklearn.metrics import zero_one_loss
zero_one_loss( y_test[y_pred_confidence], y_pred[y_pred_confidence])

0.12348509662626928

In [546]:
len(y_pred_confidence)

9159

In [547]:
sum(y_test[y_pred_confidence])

8028

In [14]:
df1['preferance_decision'] = History_vote
df1[['party_voted_past','actual_vote','Cit_pref1','lev_pref1','Cit_pref2','lev_pref2','ZIP_pref1','ZIP_pref2','preferance_decision']]

,party_voted_past,actual_vote,Cit_pref1,lev_pref1,Cit_pref2,lev_pref2,ZIP_pref1,ZIP_pref2,preferance_decision
0,Tokugawa,Tokugawa,Tokugawa,218,NONE,0,Tokugawa,Centaur,1
1,Ebony,Ebony,Ebony,81,Odyssey,39,Tokugawa,Centaur,1
2,Cosmos,Cosmos,Cosmos,87,NONE,0,Cosmos,Odyssey,1
3,Centaur,Centaur,Centaur,39,Ebony,15,Tokugawa,Ebony,1
4,Centaur,Centaur,Centaur,106,Tokugawa,49,Centaur,Tokugawa,1
5,Tokugawa,Tokugawa,Tokugawa,100,Ebony,48,Tokugawa,Ebony,1
6,Cosmos,Cosmos,Cosmos,44,Ebony,38,Odyssey,Tokugawa,1
7,Cosmos,Tokugawa,Cosmos,46,Tokugawa,38,Tokugawa,Ebony,0
8,Centaur,Centaur,Centaur,159,Odyssey,48,Centaur,Odyssey,1
9,Ebony,Centaur,Centaur,102,Ebony,15,Tokugawa,Ebony,0
10,Odyssey,Odyssey,Odyssey,123,NONE,0,Odyssey,Ebony,1
11,Cosmos,Cosmos,Cosmos,93,NONE,0,Centaur,Odyssey,1
12,Tokugawa,Tokugawa,Tokugawa,69,NONE,0,Tokugawa,Ebony,1
13,Odyssey,Odyssey,Odyssey,140,NONE,0,Odyssey,Centaur,1
14,Centaur,Centaur,Centaur,168,NONE,0,Cosmos,Centaur,1
15,Centaur,Tokugawa,Centaur,74,Ebony,36,Tokugawa,Ebony,0
16,Ebony,Cosmos,Centaur,48,Ebony,46,Ebony,Tokugawa,0
17,Centaur,Centaur,Centaur,51,Ebony,38,Cosmos,Odyssey,1
18,Cosmos,Cosmos,Cosmos,135,NONE,0,Cosmos,Odyssey,1
19,Cosmos,Centaur,Cosmos,25,NONE,0,Cosmos,Odyssey,0
20,Centaur,Centaur,Centaur,171,Ebony,19,Centaur,Cosmos,1
21,Ebony,Odyssey,Ebony,38,NONE,0,Ebony,Odyssey,0
22,Ebony,Ebony,Ebony,61,NONE,0,Ebony,Centaur,1
23,Odyssey,Odyssey,Odyssey,106,Ebony,27,Odyssey,Ebony,1
24,Ebony,Ebony,Ebony,123,Odyssey,26,Ebony,Odyssey,1
25,Ebony,Centaur,Centaur,50,Ebony,15,Ebony,Centaur,0
26,Odyssey,Odyssey,Odyssey,124,Ebony,78,Odyssey,Centaur,1
27,Cosmos,Cosmos,Odyssey,63,Ebony,27,Odyssey,Cosmos,1
28,Odyssey,Tokugawa,Odyssey,135,Cosmos,15,Odyssey,Ebony,0
29,Centaur,Cosmos,Centaur,117,Ebony,39,Centaur,Tokugawa,0
...,...,...,...,...,...,...,...,...,...
60099,Ebony,Ebony,Ebony,239,Centaur,12,Ebony,Odyssey,1
60100,Odyssey,Odyssey,Odyssey,105,Centaur,27,Odyssey,Ebony,1
60101,Tokugawa,Centaur,Centaur,27,Centaur,27,Centaur,Tokugawa,0
60102,Cosmos,Cosmos,Cosmos,54,Ebony,46,Centaur,Cosmos,1
60103,Odyssey,Odyssey,Odyssey,239,NONE,0,Odyssey,Centaur,1
60104,Centaur,Centaur,Centaur,222,NONE,0,Tokugawa,Centaur,1
60105,Cosmos,Centaur,Ebony,39,Ebony,39,Cosmos,Centaur,0
60106,Ebony,Ebony,Ebony,62,NONE,0,Odyssey,Ebony,1
60107,Centaur,Centaur,Centaur,95,NONE,0,Centaur,Tokugawa,1
60108,Odyssey,Odyssey,Odyssey,154,NONE,0,Ebony,Odyssey,1
60109,Odyssey,Odyssey,Odyssey,51,Ebony,27,Ebony,Odyssey,1
60110,Ebony,Ebony,Ebony,39,Tokugawa,36,Tokugawa,Centaur,1
60111,Centaur,Centaur,Centaur,99,NONE,0,Tokugawa,Centaur,1
60112,Ebony,Ebony,Ebony,70,NONE,0,Tokugawa,Ebony,1
60113,Odyssey,Odyssey,Odyssey,87,NONE,0,Odyssey,Ebony,1
60114,Centaur,Centaur,Centaur,130,Odyssey,72,Odyssey,Ebony,1
60115,Cosmos,Cosmos,Cosmos,39,NONE,0,Centaur,Odyssey,1
60116,Tokugawa,Tokugawa,Tokugawa,210,NONE,0,Tokugawa,Ebony,1
60117,Centaur,Centaur,Centaur,34,NONE,0,Odyssey,Ebony,1
60118,Ebony,Ebony,Ebony,62,NONE,0,Centaur,Cosmos,1
60119,Ebony,Ebony,Ebony,60,NONE,0,Odyssey,Tokugawa,1
60120,Centaur,Odyssey,Centaur,39,NONE,0,Centaur,Odyssey,0
60121,Centaur,Centaur,Centaur,99,NONE,0,Centaur,Odyssey,1
60122,Centaur,Cosmos,Centaur,51,NONE,0,Ebony,Odyssey,0
60123,Odyssey,Odyssey,Odyssey,39,Cosmos,15,Odyssey,Centaur,1
60124,Ebony,Ebony,Ebony,164,Cosmos,39,Tokugawa,Ebony,1
60125,Ebony,Ebony,Ebony,97,Tokugawa,38,Odyssey,Tokugawa,1
60126,Cosmos,Centaur,Centaur,132,Cosmos,113,Cosmos,Tokugawa,0
60127,Odyssey,Odyssey,Odyssey,87,NONE,0,Centaur,Odyssey,1
60128,Odyssey,Odyssey,Odyssey,86,NONE,0,Ebony,Odyssey,1

In [18]:
new_features_test= ['citizen_id','Ebony','Odyssey','Tokugawa','Cosmos','Centaur','Cit_pref1','Cit_pref2','city_change','ZIP_pref1','ZIP_pref2','mvar34','mvar35','mvar29','lev_pref1','lev_pref2','ZIP_lev_pref1','ZIP_lev_pref2','mvar27','mvar28','mvar31']
Feature = df1.columns[2:27]
new_features_train= ['citizen_id','Ebony','Odyssey','Tokugawa','Cosmos','Centaur','History_vote','Citizen_First_vote','Cit_pref1','Cit_pref2','city_change','ZIP_pref1','ZIP_pref2','actual_vote','mvar34','mvar35','mvar29','lev_pref1','lev_pref2','ZIP_lev_pref1','ZIP_lev_pref2','mvar27','mvar28','mvar31']

In [19]:
new_features_test = new_features_test +  list(Feature)
new_features_train = new_features_train + list(Feature)
for i in Feature:
    df1[i] = df1[i].astype(str)
    df2[i] = df2[i].astype(str)
df_train = df1[new_features_train][:]
df_test = df2[new_features_test][:]

In [20]:
df_train['mvar27'] = df_train['mvar27'].apply(str)
df_test['mvar27'] = df_test['mvar27'].apply(str)

In [21]:
Y = df_train['actual_vote']
del df_train['History_vote']
del df_train['Citizen_First_vote']
del df_train['actual_vote']
del df_train['citizen_id']
del df_test['citizen_id']

In [22]:
from sklearn.preprocessing import MinMaxScaler
MinMax = MinMaxScaler()
import warnings
warnings.filterwarnings('ignore')
df_train['lev_pref1'] = MinMax.fit_transform(df_train['lev_pref1'].values)
df_train['lev_pref2'] = MinMax.fit_transform(df_train['lev_pref2'].values)
df_train['ZIP_lev_pref1'] = MinMax.fit_transform(df_train['ZIP_lev_pref1'].values)
df_train['ZIP_lev_pref2'] = MinMax.fit_transform(df_train['ZIP_lev_pref2'].values)
df_test['lev_pref1'] = MinMax.fit_transform(df_test['lev_pref1'].values)
df_test['lev_pref2'] = MinMax.fit_transform(df_test['lev_pref2'].values)
df_test['ZIP_lev_pref1'] = MinMax.fit_transform(df_test['ZIP_lev_pref1'].values)
df_test['ZIP_lev_pref2'] = MinMax.fit_transform(df_test['ZIP_lev_pref2'].values)
df_test['ZIP_lev_pref1'] = MinMax.fit_transform(df_test['ZIP_lev_pref1'].values)
df_test['ZIP_lev_pref2'] = MinMax.fit_transform(df_test['ZIP_lev_pref2'].values)
df_test['mvar35'] = MinMax.fit_transform(df_test['mvar35'].values)
df_test['mvar34'] = MinMax.fit_transform(df_test['mvar34'].values)
df_train['mvar35'] = MinMax.fit_transform(df_train['mvar35'].values)
df_train['mvar34'] = MinMax.fit_transform(df_train['mvar34'].values)

df_train['mvar28'] = MinMax.fit_transform(df_train['mvar28'].values)
df_train['mvar31'] = MinMax.fit_transform(df_train['mvar31'].values)
df_train['mvar29'] = MinMax.fit_transform(df_train['mvar29'].values)

df_test['mvar28'] = MinMax.fit_transform(df_test['mvar28'].values)
df_test['mvar31'] = MinMax.fit_transform(df_test['mvar31'].values)
df_test['mvar29'] = MinMax.fit_transform(df_test['mvar29'].values)

In [23]:
#ENCODING
X_train = df_train.to_dict('records')
X_test = df_test.to_dict('records')
X_tr = []
X_te = []
X_tr.extend(X_train)
X_te.extend(X_test)
X_total = X_tr + X_te

In [24]:
#One Hot Encoding 
from sklearn.feature_extraction import DictVectorizer 
enc = DictVectorizer(sparse = True)
X_encoded_total =enc.fit_transform(X_total)
X_encoded_train =X_encoded_total[:len(X_tr)]
X_encoded_test =X_encoded_total[len(X_tr):]

In [25]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier,ExtraTreesClassifier,BaggingClassifier,voting_classifier
from sklearn.ensemble import AdaBoostClassifier

In [30]:
from sklearn.linear_model import LogisticRegression
clf11 = GradientBoostingClassifier(n_estimators=500,learning_rate=0.01)
clf10 = LogisticRegression(n_jobs=-1)
clf10.fit(X_encoded_train,Y)
#clf11.fit(X_encoded_train,Y)
#clf11.fit(X_encoded_train,Y_H)
#clf12.fit(X_encoded_train,Y_C)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=-1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [47]:
sol = clf10.predict(X_encoded_test.toarray())
sol_pred = clf10.predict_proba(X_encoded_test.toarray())
df2['predicted'] = sol

In [32]:
from pandas import DataFrame
df = DataFrame({'t1': sol})

In [33]:
df.to_csv('Ss65.csv')

In [36]:
df1.columns

Index([u'citizen_id', u'party_voted_past', u'mvar1', u'mvar2', u'mvar3',
       u'mvar4', u'mvar5', u'mvar6', u'mvar7', u'mvar8', u'mvar9', u'mvar10',
       u'mvar11', u'mvar12', u'mvar13', u'mvar14', u'mvar15', u'mvar16',
       u'mvar17', u'mvar18', u'mvar19', u'mvar20', u'mvar21', u'mvar22',
       u'mvar23', u'mvar24', u'mvar25', u'mvar26', u'mvar27', u'mvar28',
       u'mvar29', u'mvar30', u'mvar31', u'mvar32', u'mvar33', u'actual_vote',
       u'mvar34', u'mvar35', u'Ebony', u'Odyssey', u'Tokugawa', u'Cosmos',
       u'Centaur', u'Cit_pref1', u'lev_pref1', u'lev_pref2', u'Cit_pref2',
       u'city_change', u'ZIP_pref1', u'ZIP_pref2', u'ZIP_lev_pref1',
       u'ZIP_lev_pref2', u'History_vote', u'Citizen_First_vote'],
      dtype='object')

In [49]:
df1[['party_voted_past','actual_vote','Cit_pref1','lev_pref1','Cit_pref2','lev_pref2','ZIP_pref1','ZIP_pref2']]

,party_voted_past,actual_vote,Cit_pref1,lev_pref1,Cit_pref2,lev_pref2,ZIP_pref1,ZIP_pref2
0,Tokugawa,Tokugawa,Tokugawa,128,NONE,0,Tokugawa,Centaur
1,Ebony,Ebony,Ebony,51,Odyssey,29,Tokugawa,Centaur
2,Cosmos,Cosmos,Cosmos,57,NONE,0,Cosmos,Odyssey
3,Centaur,Centaur,Centaur,29,Ebony,15,Tokugawa,Ebony
4,Centaur,Centaur,Centaur,61,Tokugawa,34,Centaur,Tokugawa
5,Tokugawa,Tokugawa,Tokugawa,60,Ebony,33,Tokugawa,Ebony
6,Cosmos,Cosmos,Cosmos,24,Ebony,23,Odyssey,Tokugawa
7,Cosmos,Tokugawa,Cosmos,31,Tokugawa,28,Tokugawa,Ebony
8,Centaur,Centaur,Centaur,94,Odyssey,33,Centaur,Odyssey
9,Ebony,Centaur,Centaur,62,Ebony,15,Tokugawa,Ebony
10,Odyssey,Odyssey,Odyssey,78,NONE,0,Odyssey,Ebony
11,Cosmos,Cosmos,Cosmos,58,NONE,0,Centaur,Odyssey
12,Tokugawa,Tokugawa,Tokugawa,44,NONE,0,Tokugawa,Ebony
13,Odyssey,Odyssey,Odyssey,85,NONE,0,Odyssey,Centaur
14,Centaur,Centaur,Centaur,103,NONE,0,Cosmos,Centaur
15,Centaur,Tokugawa,Centaur,44,Ebony,26,Tokugawa,Ebony
16,Ebony,Cosmos,Centaur,33,Ebony,31,Ebony,Tokugawa
17,Centaur,Centaur,Centaur,36,Ebony,28,Cosmos,Odyssey
18,Cosmos,Cosmos,Cosmos,85,NONE,0,Cosmos,Odyssey
19,Cosmos,Centaur,Cosmos,20,NONE,0,Cosmos,Odyssey
20,Centaur,Centaur,Centaur,101,Ebony,14,Centaur,Cosmos
21,Ebony,Odyssey,Ebony,28,NONE,0,Ebony,Odyssey
22,Ebony,Ebony,Ebony,41,NONE,0,Ebony,Centaur
23,Odyssey,Odyssey,Odyssey,66,Ebony,22,Odyssey,Ebony
24,Ebony,Ebony,Ebony,73,Odyssey,21,Ebony,Odyssey
25,Ebony,Centaur,Centaur,35,Ebony,15,Ebony,Centaur
26,Odyssey,Odyssey,Odyssey,74,Ebony,48,Odyssey,Centaur
27,Cosmos,Cosmos,Odyssey,43,Ebony,22,Odyssey,Cosmos
28,Odyssey,Tokugawa,Odyssey,80,Cosmos,15,Odyssey,Ebony
29,Centaur,Cosmos,Centaur,67,Ebony,24,Centaur,Tokugawa
...,...,...,...,...,...,...,...,...
60099,Ebony,Ebony,Ebony,139,Centaur,7,Ebony,Odyssey
60100,Odyssey,Odyssey,Odyssey,65,Centaur,22,Odyssey,Ebony
60101,Tokugawa,Centaur,Centaur,22,Centaur,22,Centaur,Tokugawa
60102,Cosmos,Cosmos,Cosmos,34,Ebony,31,Centaur,Cosmos
60103,Odyssey,Odyssey,Odyssey,144,NONE,0,Odyssey,Centaur
60104,Centaur,Centaur,Centaur,132,NONE,0,Tokugawa,Centaur
60105,Cosmos,Centaur,Ebony,29,Ebony,29,Cosmos,Centaur
60106,Ebony,Ebony,Ebony,42,NONE,0,Odyssey,Ebony
60107,Centaur,Centaur,Centaur,60,NONE,0,Centaur,Tokugawa
60108,Odyssey,Odyssey,Odyssey,89,NONE,0,Ebony,Odyssey
60109,Odyssey,Odyssey,Odyssey,36,Ebony,22,Ebony,Odyssey
60110,Ebony,Ebony,Ebony,29,Tokugawa,26,Tokugawa,Centaur
60111,Centaur,Centaur,Centaur,64,NONE,0,Tokugawa,Centaur
60112,Ebony,Ebony,Ebony,45,NONE,0,Tokugawa,Ebony
60113,Odyssey,Odyssey,Odyssey,57,NONE,0,Odyssey,Ebony
60114,Centaur,Centaur,Centaur,80,Odyssey,47,Odyssey,Ebony
60115,Cosmos,Cosmos,Cosmos,29,NONE,0,Centaur,Odyssey
60116,Tokugawa,Tokugawa,Tokugawa,120,NONE,0,Tokugawa,Ebony
60117,Centaur,Centaur,Centaur,24,NONE,0,Odyssey,Ebony
60118,Ebony,Ebony,Ebony,42,NONE,0,Centaur,Cosmos
60119,Ebony,Ebony,Ebony,40,NONE,0,Odyssey,Tokugawa
60120,Centaur,Odyssey,Centaur,29,NONE,0,Centaur,Odyssey
60121,Centaur,Centaur,Centaur,64,NONE,0,Centaur,Odyssey
60122,Centaur,Cosmos,Centaur,36,NONE,0,Ebony,Odyssey
60123,Odyssey,Odyssey,Odyssey,29,Cosmos,15,Odyssey,Centaur
60124,Ebony,Ebony,Ebony,99,Cosmos,29,Tokugawa,Ebony
60125,Ebony,Ebony,Ebony,62,Tokugawa,28,Odyssey,Tokugawa
60126,Cosmos,Centaur,Centaur,82,Cosmos,68,Cosmos,Tokugawa
60127,Odyssey,Odyssey,Odyssey,57,NONE,0,Centaur,Odyssey
60128,Odyssey,Odyssey,Odyssey,56,NONE,0,Ebony,Odyssey

In [48]:
df2[['party_voted_past','predicted','Cit_pref1','lev_pref1','Cit_pref2','lev_pref2']]

      party_voted_past predicted Cit_pref1  lev_pref1 Cit_pref2  lev_pref2
0              Centaur   Centaur   Centaur         93     Ebony          7
1                Ebony  Tokugawa  Tokugawa         51     Ebony         46
2              Centaur   Centaur   Centaur         47      NONE          0
3                Ebony   Centaur   Odyssey        109   Centaur         99
4               Cosmos    Cosmos    Cosmos         59      NONE          0
5                Ebony     Ebony     Ebony        113   Centaur         33
6              Odyssey  Tokugawa  Tokugawa        101   Odyssey         91
7              Odyssey   Odyssey   Odyssey         89    Cosmos         31
8                Ebony     Ebony     Ebony        112      NONE          0
9              Odyssey   Odyssey   Odyssey        110     Ebony         15
10             Centaur   Centaur   Centaur         50   Odyssey         43
11             Centaur   Centaur   Centaur         88      NONE          0
12             Odyssey   Odyssey   Odyssey         81      NONE          0
13              Cosmos    Cosmos    Cosmos        112   Centaur         63
14             Odyssey   Odyssey   Odyssey        106   Centaur         36
15            Tokugawa     Ebony  Tokugawa         93   Centaur         75
16              Cosmos    Cosmos    Cosmos         27     Ebony         14
17             Centaur   Centaur   Centaur         66   Odyssey         35
18             Centaur   Odyssey   Odyssey         29   Centaur         22
19             Centaur   Odyssey   Odyssey        148   Centaur         62
20               Ebony     Ebony     Ebony         69      NONE          0
21             Odyssey   Odyssey   Odyssey         57    Cosmos         22
22               Ebony  Tokugawa  Tokugawa         50     Ebony         28
23             Centaur   Centaur   Centaur         53   Odyssey         15
24             Odyssey   Odyssey   Odyssey         43   Centaur         18
25             Odyssey   Odyssey   Odyssey         54    Cosmos         15
26             Centaur  Tokugawa   Centaur         73  Tokugawa         53
27             Centaur    Cosmos     Ebony         39    Cosmos         33
28              Cosmos  Tokugawa  Tokugawa         60    Cosmos         28
29             Centaur   Centaur   Centaur         89      NONE          0
...                ...       ...       ...        ...       ...        ...
21177           Cosmos    Cosmos    Cosmos         51     Ebony          7
21178         Tokugawa  Tokugawa  Tokugawa         91     Ebony         34
21179          Centaur   Centaur   Centaur         33      NONE          0
21180          Centaur   Odyssey   Odyssey         33   Centaur         29
21181           Cosmos    Cosmos    Cosmos         54      NONE          0
21182           Cosmos     Ebony     Ebony         65    Cosmos         29
21183          Centaur    Cosmos   Odyssey         29    Cosmos         22
21184          Odyssey   Odyssey   Odyssey         65      NONE          0
21185          Centaur   Centaur   Centaur         35     Ebony         33
21186         Tokugawa  Tokugawa  Tokugawa         90   Odyssey         26
21187           Cosmos    Cosmos    Cosmos         33      NONE          0
21188            Ebony     Ebony     Ebony         82      NONE          0
21189            Ebony     Ebony     Ebony        138      NONE          0
21190          Centaur   Centaur   Centaur         59     Ebony         22
21191            Ebony     Ebony     Ebony         83      NONE          0
21192            Ebony     Ebony     Ebony         35      NONE          0
21193           Cosmos    Cosmos  Tokugawa         66    Cosmos         59
21194          Centaur  Tokugawa   Centaur         25  Tokugawa         19
21195           Cosmos    Cosmos    Cosmos         75      NONE          0
21196          Centaur   Centaur   Centaur         80   Odyssey         36
21197          Centaur   Centaur   Centaur        111     Ebony         35
21198           Cosmos    Cosmos    Cosmos         77      NONE          0
21199            Ebony   Odyssey   Odyssey         57     Ebony         15
21200            Ebony     Ebony     Ebony        112    Cosmos          7
21201           Cosmos    Cosmos    Cosmos         96      NONE          0
21202          Odyssey   Odyssey   Odyssey        117      NONE          0
21203           Cosmos  Tokugawa  Tokugawa         72   Centaur         46
21204           Cosmos   Centaur   Centaur         22   Centaur         22
21205          Odyssey   Odyssey   Odyssey         50      NONE          0
21206           Cosmos    Cosmos    Cosmos         61      NONE          0

[21207 rows x 6 columns]

In [54]:
Voted_first_priorty = []
History_vote = []
for i in range(len(df1)):
    if df1['party_voted_past'].values[i] == df1['actual_vote'].values[i]:
        History_vote.append(1)
        Voted_first_priorty.append(i)
    else:
        History_vote.append(0)

In [53]:
sum(History_vote)

45116

In [57]:
df1.drop(df1.index[Voted_first_priorty])[['party_voted_past','actual_vote','Cit_pref1','lev_pref1','Cit_pref2','lev_pref2','ZIP_pref1','ZIP_pref2']]

,party_voted_past,actual_vote,Cit_pref1,lev_pref1,Cit_pref2,lev_pref2,ZIP_pref1,ZIP_pref2
7,Cosmos,Tokugawa,Cosmos,31,Tokugawa,28,Tokugawa,Ebony
9,Ebony,Centaur,Centaur,62,Ebony,15,Tokugawa,Ebony
15,Centaur,Tokugawa,Centaur,44,Ebony,26,Tokugawa,Ebony
16,Ebony,Cosmos,Centaur,33,Ebony,31,Ebony,Tokugawa
19,Cosmos,Centaur,Cosmos,20,NONE,0,Cosmos,Odyssey
21,Ebony,Odyssey,Ebony,28,NONE,0,Ebony,Odyssey
25,Ebony,Centaur,Centaur,35,Ebony,15,Ebony,Centaur
28,Odyssey,Tokugawa,Odyssey,80,Cosmos,15,Odyssey,Ebony
29,Centaur,Cosmos,Centaur,67,Ebony,24,Centaur,Tokugawa
33,Ebony,Cosmos,Cosmos,51,Ebony,40,Cosmos,Odyssey
37,Ebony,Centaur,Centaur,36,Ebony,31,Ebony,Centaur
50,Centaur,Tokugawa,Centaur,33,Odyssey,28,Odyssey,Tokugawa
52,Odyssey,Tokugawa,Tokugawa,46,Odyssey,37,Ebony,Tokugawa
59,Centaur,Cosmos,Ebony,41,Centaur,37,Centaur,Tokugawa
64,Centaur,Cosmos,Centaur,40,Cosmos,29,Cosmos,Centaur
65,Cosmos,Ebony,Ebony,33,Centaur,29,Centaur,Odyssey
69,Odyssey,Cosmos,Odyssey,29,Centaur,22,Odyssey,Ebony
74,Cosmos,Tokugawa,Tokugawa,37,Tokugawa,37,Odyssey,Tokugawa
75,Tokugawa,Centaur,Centaur,68,Tokugawa,65,Tokugawa,Centaur
77,Centaur,Odyssey,Cosmos,22,Centaur,14,Cosmos,Centaur
79,Ebony,Tokugawa,Tokugawa,72,Ebony,55,Tokugawa,Centaur
85,Centaur,Cosmos,Centaur,29,Cosmos,22,Centaur,Odyssey
89,Cosmos,Ebony,Cosmos,36,NONE,0,Odyssey,Ebony
95,Ebony,Cosmos,Ebony,33,Odyssey,28,Cosmos,Odyssey
97,Odyssey,Centaur,Centaur,78,Centaur,78,Odyssey,Centaur
98,Centaur,Cosmos,Centaur,49,Cosmos,27,Cosmos,Ebony
105,Odyssey,Ebony,Odyssey,22,Ebony,15,Odyssey,Centaur
108,Ebony,Centaur,Centaur,67,Ebony,30,Tokugawa,Centaur
117,Odyssey,Centaur,Odyssey,44,Cosmos,7,Centaur,Odyssey
123,Odyssey,Tokugawa,Odyssey,51,NONE,0,Cosmos,Tokugawa
...,...,...,...,...,...,...,...,...
59996,Tokugawa,Odyssey,Odyssey,36,Tokugawa,33,Odyssey,Centaur
60002,Centaur,Cosmos,Centaur,85,Ebony,22,Ebony,Odyssey
60004,Centaur,Ebony,Centaur,57,Ebony,21,Centaur,Odyssey
60005,Odyssey,Tokugawa,Odyssey,37,Tokugawa,29,Tokugawa,Ebony
60008,Centaur,Cosmos,Cosmos,58,Centaur,45,Cosmos,Centaur
60010,Centaur,Ebony,Centaur,64,Odyssey,22,Ebony,Odyssey
60020,Centaur,Cosmos,Centaur,22,Cosmos,11,Centaur,Odyssey
60023,Cosmos,Ebony,Cosmos,85,Ebony,48,Ebony,Tokugawa
60024,Tokugawa,Cosmos,Tokugawa,32,Ebony,26,Cosmos,Ebony
60029,Centaur,Cosmos,Ebony,29,Centaur,21,Centaur,Cosmos
60032,Cosmos,Centaur,Centaur,22,Centaur,22,Cosmos,Centaur
60034,Tokugawa,Ebony,Tokugawa,57,Ebony,22,Tokugawa,Ebony
60038,Ebony,Centaur,Centaur,58,Ebony,43,Ebony,Tokugawa
60040,Ebony,Centaur,Centaur,47,Ebony,43,Centaur,Ebony
60044,Cosmos,Tokugawa,Cosmos,64,Centaur,22,Cosmos,Tokugawa
60047,Cosmos,Centaur,Cosmos,22,Centaur,21,Centaur,Odyssey
60054,Centaur,Odyssey,Centaur,50,Odyssey,36,Centaur,Odyssey
60058,Centaur,Ebony,Odyssey,29,Ebony,22,Odyssey,Centaur
60059,Odyssey,Cosmos,Odyssey,26,Cosmos,22,Cosmos,Tokugawa
60063,Cosmos,Odyssey,Cosmos,56,Odyssey,26,Centaur,Cosmos
60068,Tokugawa,Odyssey,Tokugawa,98,Odyssey,31,Tokugawa,Ebony
60073,Cosmos,Centaur,Tokugawa,24,Cosmos,19,Tokugawa,Centaur
60074,Centaur,Odyssey,Odyssey,58,Centaur,32,Odyssey,Centaur
60084,Odyssey,Cosmos,Odyssey,40,Tokugawa,26,Tokugawa,Centaur
60090,Cosmos,Ebony,Cosmos,36,Centaur,22,Cosmos,Centaur
60101,Tokugawa,Centaur,Centaur,22,Centaur,22,Centaur,Tokugawa
60105,Cosmos,Centaur,Ebony,29,Ebony,29,Cosmos,Centaur
60120,Centaur,Odyssey,Centaur,29,NONE,0,Centaur,Odyssey
60122,Centaur,Cosmos,Centaur,36,NONE,0,Ebony,Odyssey
60126,Cosmos,Centaur,Centaur,82,Cosmos,68,Cosmos,Tokugawa

In [16]:
df1['bro'] = [df1['party_voted_past'],df1['mvar2']]

ValueError: Length of values does not match length of index